### ISSUE TITLE
Upgrade to Dart 2

### ISSUE THREAD

**Issue by Morosko** [MarcinusX/sliver_fab#2]
First things first: great plugin. Thanks for that. Could you please update to Dart 2, so we can keep using it in our App? I would do it myself and send you a PR, but I don't have the resources to make myself familiar with your plugin ATM. Maybe you just have to change your pubspec.yaml. Would really appreciate the update.

**Comment by MarcinusX** [comment]
@Morosko Thanks for the reminder! Just published the updated version. Please reopen if it still occurs.
